// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Check if the service is running and healthy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/anomaly/check": {
            "post": {
                "description": "Evaluate if a given request latency is anomalous based on historical baselines\nThe service uses time-bucketed baselines (per hour and day type) and statistical methods (P50, P95, MAD) to detect anomalies\nFallback: Automatically applies a 5-level strategy to select a baseline\n(exact → nearby → daytype → global → unavailable) when the exact bucket has insufficient data.\nResponse fields:\n- baselineSource: which source was used (exact/nearby/daytype/global/unavailable)\n- fallbackLevel: numeric level 1-5 mapping to the source (1=exact, 2=nearby, 3=daytype, 4=global, 5=unavailable)\n- sourceDetails: human-readable details about the selected source (e.g. \"exact match: 17|weekday\")\n- cannotDetermine: true if no sufficient baseline exists to decide",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anomaly Detection"
                ],
                "summary": "Check for latency anomaly",
                "parameters": [
                    {
                        "description": "Anomaly check request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AnomalyCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Includes baselineSource, fallbackLevel, sourceDetails, cannotDetermine",
                        "schema": {
                            "$ref": "#/definitions/domain.AnomalyCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service not available",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/available": {
            "get": {
                "description": "Retrieve all services and endpoints that have sufficient baseline samples for anomaly detection\nReturns a list of service/endpoint pairs grouped by service, along with their available time buckets\nOnly includes baselines with sufficient samples (configured via min_samples)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Available Services"
                ],
                "summary": "List available services and endpoints",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AvailableServicesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service not available",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/baseline": {
            "get": {
                "description": "Retrieve baseline statistics (P50, P95, MAD) for a specific service, endpoint, hour, and day type\nUsed for debugging and monitoring baseline data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Baseline"
                ],
                "summary": "Get baseline statistics",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"twdiw-customer-service-prod\"",
                        "description": "Service name",
                        "name": "service",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"GET /actuator/health\"",
                        "description": "Endpoint name",
                        "name": "endpoint",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 16,
                        "description": "Hour of day (0-23)",
                        "name": "hour",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"weekday\"",
                        "description": "Day type (weekday or weekend)",
                        "name": "dayType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Baseline"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Baseline not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Store not available",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AnomalyCheckRequest": {
            "type": "object",
            "properties": {
                "durationMs": {
                    "type": "integer",
                    "example": 5
                },
                "endpoint": {
                    "type": "string",
                    "example": "AiPromptSyncScheduler.syncAiPromptsToDify"
                },
                "service": {
                    "type": "string",
                    "example": "twdiw-customer-service-prod"
                },
                "timestampNano": {
                    "type": "integer",
                    "example": 1737000000000000000
                }
            }
        },
        "domain.AnomalyCheckResponse": {
            "type": "object",
            "properties": {
                "baseline": {
                    "$ref": "#/definitions/domain.BaselineStats"
                },
                "baselineSource": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.BaselineSource"
                        }
                    ],
                    "example": "exact"
                },
                "bucket": {
                    "$ref": "#/definitions/domain.TimeBucket"
                },
                "cannotDetermine": {
                    "type": "boolean",
                    "example": false
                },
                "explanation": {
                    "type": "string",
                    "example": "duration 5ms within threshold 2.00ms"
                },
                "fallbackLevel": {
                    "type": "integer",
                    "example": 1
                },
                "isAnomaly": {
                    "type": "boolean",
                    "example": false
                },
                "sourceDetails": {
                    "type": "string",
                    "example": "exact match: 9|weekday"
                }
            }
        },
        "domain.AvailableServicesResponse": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ServiceEndpoint"
                    }
                },
                "totalEndpoints": {
                    "type": "integer",
                    "example": 17
                },
                "totalServices": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "domain.BaselineSource": {
            "type": "string",
            "enum": [
                "exact",
                "nearby",
                "daytype",
                "global",
                "unavailable"
            ],
            "x-enum-comments": {
                "SourceDayType": "Level 3: All hours of same day type",
                "SourceExact": "Level 1: Exact hour|dayType match",
                "SourceGlobal": "Level 4: All data (any hour, any day type)",
                "SourceNearby": "Level 2: Nearby hours (±1, ±2)",
                "SourceUnavailable": "Level 5: No data available"
            },
            "x-enum-descriptions": [
                "Level 1: Exact hour|dayType match",
                "Level 2: Nearby hours (±1, ±2)",
                "Level 3: All hours of same day type",
                "Level 4: All data (any hour, any day type)",
                "Level 5: No data available"
            ],
            "x-enum-varnames": [
                "SourceExact",
                "SourceNearby",
                "SourceDayType",
                "SourceGlobal",
                "SourceUnavailable"
            ]
        },
        "domain.BaselineStats": {
            "type": "object",
            "properties": {
                "mad": {
                    "type": "number",
                    "example": 0
                },
                "p50": {
                    "type": "number",
                    "example": 1
                },
                "p95": {
                    "type": "number",
                    "example": 2
                },
                "sampleCount": {
                    "type": "integer",
                    "example": 188
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2026-01-16T02:00:00Z"
                }
            }
        },
        "domain.ServiceEndpoint": {
            "type": "object",
            "properties": {
                "buckets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "6|weekday",
                        "9|weekday",
                        "10|weekday",
                        "12|weekday",
                        "13|weekend",
                        "17|weekday",
                        "20|weekday"
                    ]
                },
                "endpoint": {
                    "type": "string",
                    "example": "AiPromptSyncScheduler.syncAiPromptsToDify"
                },
                "service": {
                    "type": "string",
                    "example": "twdiw-customer-service-prod"
                }
            }
        },
        "domain.TimeBucket": {
            "type": "object",
            "properties": {
                "dayType": {
                    "description": "\"weekday\" or \"weekend\"",
                    "type": "string",
                    "example": "weekday"
                },
                "hour": {
                    "description": "0-23",
                    "type": "integer",
                    "example": 9
                }
            }
        },
        "handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "store.Baseline": {
            "type": "object",
            "properties": {
                "mad": {
                    "type": "number",
                    "example": 43
                },
                "p50": {
                    "type": "number",
                    "example": 233.5
                },
                "p95": {
                    "type": "number",
                    "example": 562
                },
                "sampleCount": {
                    "type": "integer",
                    "example": 50
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2026-01-15T08:00:00Z"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Health check endpoints",
            "name": "Health"
        },
        {
            "description": "Anomaly detection and evaluation endpoints",
            "name": "Anomaly Detection"
        },
        {
            "description": "Baseline statistics query endpoints",
            "name": "Baseline"
        },
        {
            "description": "Query available services and endpoints with sufficient baseline data",
            "name": "Available Services"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Tempo Latency Anomaly Detection Service API",
	Description:      "Time-Aware API Latency Anomaly Detection Service based on Grafana Tempo traces\n\nThis service provides real-time latency anomaly detection using statistical methods (P50, P95, MAD).\nIt automatically ingests traces from Tempo and maintains time-bucketed baselines per (service, endpoint, hour, dayType).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
